'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const P=require('../src/agent-plan'),M=require('../renderer/report-model');
const request=(input,extra=[])=>P.parseArgs(['app','--luma-agent','export',input,'--output',path.join(path.dirname(input),'out.pdf'),...extra]);
test('Agent help is self describing and parser rejects missing or unknown arguments',()=>{assert.equal(P.parseArgs(['exe','--luma-agent','--help']).command,'help');assert.equal(P.help('1.5').protocol,'lumareader.agent/v1');for(const args of [[],['--luma-agent','wrong'],['--luma-agent','export','a.md'],['--luma-agent','inspect','a.md','--unknown'],['--luma-agent','export','a.md','--output'],['--luma-agent','export','a.md','--output','one.pdf','--output','two.pdf']])assert.throws(()=>P.parseArgs(args));assert.equal(request('/tmp/file with spaces.md',['--plain']).options['--plain'],true);});
test('Agent recipe stacks several short blocks in one right column without modifying Markdown',()=>{const text='# Report\n\nLong.\n\nShort one.\n\nShort two.\n',recipe={schema:P.PROTOCOL,options:{pageSize:'A4'},placements:[{blocks:[3],target:2,position:'right'},{blocks:[4],target:3,position:'below'}],styles:[{blocks:[3,4],fontSize:12}],columns:[{block:2,weights:[2,1],dividers:[true]}]};const {layout,items}=P.buildLayout(text,recipe);const row=layout.rows[M.locate(layout,items[1].id).row];assert.deepEqual(row.cells.map(c=>c.blocks),[[items[1].id],[items[2].id,items[3].id]]);assert.equal(row.weights[0]/row.weights[1],2);assert.equal(layout.styles[items[3].id].fontSize,12);assert.equal(items.map(i=>i.source).join(''),text);});
test('Agent validates document hashes, selectors and style bounds instead of silently ignoring mistakes',()=>{const text='one\n\ntwo\n';for(const recipe of [{schema:P.PROTOCOL,sourceHash:'stale'},{schema:'wrong'},{schema:P.PROTOCOL,extra:true},{schema:P.PROTOCOL,placements:[{blocks:[9],target:1,position:'right'}]},{schema:P.PROTOCOL,styles:[{blocks:[1],fontSize:2}]},{schema:P.PROTOCOL,options:{fontSize:50}},{schema:P.PROTOCOL,options:{colorFrame:'false'}}])assert.throws(()=>P.buildLayout(text,recipe,{},'new'));assert.throws(()=>P.buildLayout(text,null,{pageSize:'bad'}));});
test('Agent App layouts retain PDF-only text metadata, options and block styles',()=>{const text='one\n\ntwo\n',base=P.buildLayout(text).layout;base.styles[base.anchors[1].id]={spaceBefore:40};const {layout}=P.buildLayout(text,base,{colorFrame:false});assert.equal(layout.styles[base.anchors[1].id].spaceBefore,40);assert.equal(layout.options.colorFrame,false);});
async function fixture(fn){const root=await fs.mkdtemp(path.join(os.tmpdir(),'luma-agent-unit-'));try{const input=path.join(root,'Doc.md');await fs.writeFile(input,'\ufeff# Original\r\n\r\nText.\r\n');await fn(root,input);}finally{await fs.rm(root,{recursive:true,force:true});}}
test('Agent reads explicit local Markdown, maintains bytes and returns stable inspect block IDs',()=>fixture(async(root,input)=>{const job=await P.readJob(request(input));assert.equal(job.root,await fs.realpath(root));assert.equal(job.layout.options.colorFrame,true);assert.equal(P.inspect(job).blocks[0].index,1);assert.equal(P.inspect(job).blocks[0].id,P.inspect(await P.readJob(request(input))).blocks[0].id);assert.equal(job.allowRemote,false);assert.equal(await fs.readFile(input,'utf8'),'\ufeff# Original\r\n\r\nText.\r\n');}));
test('Agent refuses input outside root, unsupported files, invalid layout and invalid accent',()=>fixture(async(root,input)=>{const other=path.join(root,'other');await fs.mkdir(other);await assert.rejects(()=>P.readJob(request(input,['--root',other])));await fs.writeFile(path.join(root,'a.py'),'print(1)');await assert.rejects(()=>P.readJob(request(path.join(root,'a.py'))));const recipe=path.join(root,'layout.json');for(const value of ['broken','null','[]']){await fs.writeFile(recipe,value);await assert.rejects(()=>P.readJob(request(input,['--layout',recipe])));}await assert.rejects(()=>P.readJob(request(input,['--accent','red;script'])));}));
test('Agent PDF output is exclusive by default and overwrites only with an explicit flag',()=>fixture(async(root,input)=>{const job=await P.readJob(request(input)),bytes=Buffer.from('%PDF-first');await P.savePdf(job,bytes);assert.deepEqual(await fs.readFile(job.output),bytes);await assert.rejects(()=>P.readJob(request(input)),{code:'OUTPUT_EXISTS'});await assert.rejects(()=>P.savePdf(job,Buffer.from('%PDF-race')),{code:'OUTPUT_EXISTS'});await P.savePdf(await P.readJob(request(input,['--overwrite'])),Buffer.from('%PDF-new'));assert.equal(await fs.readFile(job.output,'utf8'),'%PDF-new');assert.equal((await fs.readdir(root)).some(n=>n.endsWith('.tmp')),false);}));
test('Agent refuses source changes, non-PDF bytes and symlink output pointing at Markdown',()=>fixture(async(root,input)=>{const job=await P.readJob(request(input));await assert.rejects(()=>P.savePdf(job,Buffer.from('not PDF')));await fs.appendFile(input,'changed');await assert.rejects(()=>P.savePdf(job,Buffer.from('%PDF-safe')),{code:'SOURCE_CHANGED'});await fs.symlink(input,job.output);await assert.rejects(()=>P.readJob(request(input,['--overwrite'])));assert.ok((await fs.readFile(input,'utf8')).endsWith('changed'));}));
