'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const {install,argumentsOf}=require('../tools/embed-cli/embed.cjs');
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'luma-embed-cli-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));return root;}
test('installer creates a complete HTML page with the original Reader loader',async t=>{const root=await fixture(t),target=path.join(root,'index.html');const result=await install({output:target});assert.equal(result.backup,null);const html=await fs.readFile(target,'utf8');assert.match(html,/https:\/\/lumareader.kainnne.com\/embed\/install.js/);assert.ok(html.indexOf('data-luma-target')<html.indexOf('</body>'));});
test('installer backs up existing HTML exactly and refuses a duplicate installation',async t=>{const root=await fixture(t),target=path.join(root,'index.html'),original='<!doctype html><html><body><h1>原網站</h1></body></html>';await fs.writeFile(target,original);const result=await install({output:target});assert.equal(await fs.readFile(result.backup,'utf8'),original);assert.match(await fs.readFile(target,'utf8'),/<h1>原網站<\/h1>/);await assert.rejects(install({output:target}),/已加入/);});
test('Markdown is preserved as JSON and cannot close the script tag',async t=>{const root=await fixture(t),target=path.join(root,'index.html'),markdown=path.join(root,'test.md'),text='# 中文\n\n</script><script>alert(1)</script>\n';await fs.writeFile(markdown,text);await install({output:target,markdown});const html=await fs.readFile(target,'utf8');assert.doesNotMatch(html,/<script>alert/);assert.equal(JSON.parse(html.match(/type="application\/json"[^>]*>(.*?)<\/script>/s)[1]).markdown,text);});
test('invalid paths, fragments, and unsupported arguments are rejected',async t=>{const root=await fixture(t),target=path.join(root,'part.html');await fs.writeFile(target,'<div>fragment</div>');await assert.rejects(install({output:target}),/body/);await assert.rejects(install({output:path.join(root,'app.js')}),/html/);assert.throws(()=>argumentsOf(['--unknown']),/參數/);assert.deepEqual(argumentsOf(['index.html','--markdown','稿件.md']),{output:'index.html',markdown:'稿件.md'});});
test('published v1 tool remains archived and generated HTML keeps the permanent loader contract',async()=>{const pkg=require('../tools/embed-cli/package.json');await fs.access(path.resolve(__dirname,'../tools/embed-cli/releases/lumareader-embed-'+pkg.version+'.tgz'));const fixture=await fs.readFile(path.join(__dirname,'fixtures/embed-v1.html'),'utf8');assert.match(fixture,/https:\/\/lumareader.kainnne.com\/embed\/install.js/);assert.match(fixture,/data-luma-document="original-luma-document"/);});
