(function () {
  "use strict";

  const SUPPORTED_EXTENSIONS = [".md", ".mkd", ".mdx", ".markdown"];
  const translations = {
    en: { library:"Document Library",sourcePlaceholder:"Paste file://, http:// or https://",openSource:"Open source",chooseFile:"Choose local document",search:"Search documents",rescan:"Rescan",navigation:"Navigation",files:"Files",outline:"Outline",documents:"Documents",ready:"Ready",readerSettings:"Reader settings",readingMode:"Reading mode",vertical:"Vertical",horizontal:"Horizontal",paged:"Paged",source:"Source",media:"Media",smallerText:"Smaller text",largerText:"Larger text",palette:"Color palette",language:"Interface language",darkMode:"Dark mode",lightMode:"Light mode",fullscreen:"Fullscreen",empty:"Choose a document to begin.",mediaPreview:"Media Preview",close:"Close",live:"Live",loading:"Loading…",loadError:"Unable to open this document.",refreshed:"Document refreshed",renderedView:"Rendered view",sourceView:"Source view",noOutline:"No headings in this document.",noMedia:"No media in this document.",copy:"Copy",copied:"Copied",invalidSource:"Enter a file://, http://, https:// or local path.",noMatches:"No matching documents." },
    "zh-Hant": { library:"文件資料庫",sourcePlaceholder:"貼上 file://、http:// 或 https://",openSource:"開啟來源",chooseFile:"選擇本機文件",search:"搜尋文件",rescan:"重新掃描",navigation:"導覽",files:"檔案",outline:"目錄",documents:"文件",ready:"準備完成",readerSettings:"閱讀設定",readingMode:"閱讀模式",vertical:"直式",horizontal:"橫式",paged:"翻頁",source:"原文",media:"媒體",smallerText:"縮小文字",largerText:"放大文字",palette:"色系",language:"介面語言",darkMode:"深色模式",lightMode:"明亮模式",fullscreen:"全螢幕",empty:"選擇一份文件開始閱讀。",mediaPreview:"媒體預覽",close:"關閉",live:"即時",loading:"載入中…",loadError:"無法開啟這份文件。",refreshed:"文件已更新",renderedView:"閱讀畫面",sourceView:"原始內容",noOutline:"這份文件沒有標題目錄。",noMedia:"這份文件沒有媒體。",copy:"複製",copied:"已複製",invalidSource:"請輸入 file://、http://、https:// 或本機路徑。",noMatches:"找不到符合的文件。" },
    "zh-Hans": { library:"文档资料库",sourcePlaceholder:"粘贴 file://、http:// 或 https://",openSource:"打开来源",chooseFile:"选择本地文档",search:"搜索文档",rescan:"重新扫描",navigation:"导航",files:"文件",outline:"目录",documents:"文档",ready:"准备完成",readerSettings:"阅读设置",readingMode:"阅读模式",vertical:"纵向",horizontal:"横向",paged:"翻页",source:"原文",media:"媒体",smallerText:"缩小文字",largerText:"放大文字",palette:"配色",language:"界面语言",darkMode:"深色模式",lightMode:"浅色模式",fullscreen:"全屏",empty:"选择一份文档开始阅读。",mediaPreview:"媒体预览",close:"关闭",live:"实时",loading:"加载中…",loadError:"无法打开此文档。",refreshed:"文档已更新",renderedView:"阅读视图",sourceView:"原始内容",noOutline:"此文档没有标题目录。",noMedia:"此文档没有媒体。",copy:"复制",copied:"已复制",invalidSource:"请输入 file://、http://、https:// 或本地路径。",noMatches:"没有匹配的文档。" },
    ja: { library:"ドキュメントライブラリ",sourcePlaceholder:"file://、http://、https:// を貼り付け",openSource:"ソースを開く",chooseFile:"ローカル文書を選択",search:"文書を検索",rescan:"再スキャン",navigation:"ナビゲーション",files:"ファイル",outline:"目次",documents:"文書",ready:"準備完了",readerSettings:"閲覧設定",readingMode:"閲覧モード",vertical:"縦書き表示",horizontal:"横スクロール",paged:"ページ",source:"ソース",media:"メディア",smallerText:"文字を小さく",largerText:"文字を大きく",palette:"カラーテーマ",language:"表示言語",darkMode:"ダークモード",lightMode:"ライトモード",fullscreen:"全画面",empty:"文書を選択してください。",mediaPreview:"メディアプレビュー",close:"閉じる",live:"ライブ",loading:"読み込み中…",loadError:"文書を開けません。",refreshed:"文書を更新しました",renderedView:"プレビュー",sourceView:"ソース表示",noOutline:"見出しがありません。",noMedia:"メディアがありません。",copy:"コピー",copied:"コピーしました",invalidSource:"有効な URL またはローカルパスを入力してください。",noMatches:"一致する文書がありません。" },
    ko: { library:"문서 라이브러리",sourcePlaceholder:"file://, http:// 또는 https:// 붙여넣기",openSource:"소스 열기",chooseFile:"로컬 문서 선택",search:"문서 검색",rescan:"다시 검색",navigation:"탐색",files:"파일",outline:"목차",documents:"문서",ready:"준비됨",readerSettings:"읽기 설정",readingMode:"읽기 모드",vertical:"세로",horizontal:"가로",paged:"페이지",source:"원문",media:"미디어",smallerText:"글자 축소",largerText:"글자 확대",palette:"색상 테마",language:"인터페이스 언어",darkMode:"다크 모드",lightMode:"라이트 모드",fullscreen:"전체 화면",empty:"문서를 선택해 읽기를 시작하세요.",mediaPreview:"미디어 미리보기",close:"닫기",live:"실시간",loading:"불러오는 중…",loadError:"문서를 열 수 없습니다.",refreshed:"문서가 업데이트되었습니다",renderedView:"읽기 화면",sourceView:"원문 보기",noOutline:"제목 목차가 없습니다.",noMedia:"미디어가 없습니다.",copy:"복사",copied:"복사됨",invalidSource:"유효한 URL 또는 로컬 경로를 입력하세요.",noMatches:"일치하는 문서가 없습니다." },
    es: { library:"Biblioteca de documentos",sourcePlaceholder:"Pega file://, http:// o https://",openSource:"Abrir origen",chooseFile:"Elegir documento local",search:"Buscar documentos",rescan:"Volver a analizar",navigation:"Navegación",files:"Archivos",outline:"Índice",documents:"Documentos",ready:"Listo",readerSettings:"Ajustes de lectura",readingMode:"Modo de lectura",vertical:"Vertical",horizontal:"Horizontal",paged:"Páginas",source:"Fuente",media:"Medios",smallerText:"Texto más pequeño",largerText:"Texto más grande",palette:"Paleta de colores",language:"Idioma",darkMode:"Modo oscuro",lightMode:"Modo claro",fullscreen:"Pantalla completa",empty:"Elige un documento para comenzar.",mediaPreview:"Vista multimedia",close:"Cerrar",live:"En vivo",loading:"Cargando…",loadError:"No se puede abrir el documento.",refreshed:"Documento actualizado",renderedView:"Vista renderizada",sourceView:"Código fuente",noOutline:"No hay encabezados.",noMedia:"No hay contenido multimedia.",copy:"Copiar",copied:"Copiado",invalidSource:"Introduce una URL o ruta local válida.",noMatches:"No hay documentos coincidentes." },
    fr: { library:"Bibliothèque de documents",sourcePlaceholder:"Collez file://, http:// ou https://",openSource:"Ouvrir la source",chooseFile:"Choisir un document local",search:"Rechercher",rescan:"Réanalyser",navigation:"Navigation",files:"Fichiers",outline:"Plan",documents:"Documents",ready:"Prêt",readerSettings:"Réglages de lecture",readingMode:"Mode de lecture",vertical:"Vertical",horizontal:"Horizontal",paged:"Pages",source:"Source",media:"Médias",smallerText:"Réduire le texte",largerText:"Agrandir le texte",palette:"Palette",language:"Langue",darkMode:"Mode sombre",lightMode:"Mode clair",fullscreen:"Plein écran",empty:"Choisissez un document pour commencer.",mediaPreview:"Aperçu des médias",close:"Fermer",live:"Direct",loading:"Chargement…",loadError:"Impossible d’ouvrir ce document.",refreshed:"Document actualisé",renderedView:"Aperçu",sourceView:"Code source",noOutline:"Aucun titre dans ce document.",noMedia:"Aucun média dans ce document.",copy:"Copier",copied:"Copié",invalidSource:"Saisissez une URL ou un chemin local valide.",noMatches:"Aucun document correspondant." },
    de: { library:"Dokumentbibliothek",sourcePlaceholder:"file://, http:// oder https:// einfügen",openSource:"Quelle öffnen",chooseFile:"Lokales Dokument wählen",search:"Dokumente suchen",rescan:"Neu einlesen",navigation:"Navigation",files:"Dateien",outline:"Gliederung",documents:"Dokumente",ready:"Bereit",readerSettings:"Leseeinstellungen",readingMode:"Lesemodus",vertical:"Vertikal",horizontal:"Horizontal",paged:"Seiten",source:"Quelltext",media:"Medien",smallerText:"Text verkleinern",largerText:"Text vergrößern",palette:"Farbpalette",language:"Sprache",darkMode:"Dunkelmodus",lightMode:"Hellmodus",fullscreen:"Vollbild",empty:"Wähle ein Dokument aus.",mediaPreview:"Medienvorschau",close:"Schließen",live:"Live",loading:"Wird geladen…",loadError:"Dokument kann nicht geöffnet werden.",refreshed:"Dokument aktualisiert",renderedView:"Vorschau",sourceView:"Quelltextansicht",noOutline:"Keine Überschriften vorhanden.",noMedia:"Keine Medien vorhanden.",copy:"Kopieren",copied:"Kopiert",invalidSource:"Gib eine gültige URL oder einen lokalen Pfad ein.",noMatches:"Keine passenden Dokumente." },
    "pt-BR": { library:"Biblioteca de documentos",sourcePlaceholder:"Cole file://, http:// ou https://",openSource:"Abrir origem",chooseFile:"Escolher documento local",search:"Buscar documentos",rescan:"Verificar novamente",navigation:"Navegação",files:"Arquivos",outline:"Sumário",documents:"Documentos",ready:"Pronto",readerSettings:"Configurações de leitura",readingMode:"Modo de leitura",vertical:"Vertical",horizontal:"Horizontal",paged:"Páginas",source:"Fonte",media:"Mídia",smallerText:"Texto menor",largerText:"Texto maior",palette:"Paleta de cores",language:"Idioma",darkMode:"Modo escuro",lightMode:"Modo claro",fullscreen:"Tela cheia",empty:"Escolha um documento para começar.",mediaPreview:"Prévia de mídia",close:"Fechar",live:"Ao vivo",loading:"Carregando…",loadError:"Não foi possível abrir o documento.",refreshed:"Documento atualizado",renderedView:"Visualização",sourceView:"Código-fonte",noOutline:"Nenhum título encontrado.",noMedia:"Nenhuma mídia encontrada.",copy:"Copiar",copied:"Copiado",invalidSource:"Digite uma URL ou caminho local válido.",noMatches:"Nenhum documento correspondente." },
    ru: { library:"Библиотека документов",sourcePlaceholder:"Вставьте file://, http:// или https://",openSource:"Открыть источник",chooseFile:"Выбрать локальный документ",search:"Поиск документов",rescan:"Обновить список",navigation:"Навигация",files:"Файлы",outline:"Содержание",documents:"Документы",ready:"Готово",readerSettings:"Настройки чтения",readingMode:"Режим чтения",vertical:"Вертикально",horizontal:"Горизонтально",paged:"Страницы",source:"Исходник",media:"Медиа",smallerText:"Уменьшить текст",largerText:"Увеличить текст",palette:"Цветовая палитра",language:"Язык интерфейса",darkMode:"Тёмная тема",lightMode:"Светлая тема",fullscreen:"Полный экран",empty:"Выберите документ, чтобы начать.",mediaPreview:"Просмотр медиа",close:"Закрыть",live:"Автообновление",loading:"Загрузка…",loadError:"Не удалось открыть документ.",refreshed:"Документ обновлён",renderedView:"Предпросмотр",sourceView:"Исходный текст",noOutline:"В документе нет заголовков.",noMedia:"В документе нет медиа.",copy:"Копировать",copied:"Скопировано",invalidSource:"Введите корректный URL или локальный путь.",noMatches:"Совпадений не найдено." },
    it: { library:"Libreria documenti",sourcePlaceholder:"Incolla file://, http:// o https://",openSource:"Apri origine",chooseFile:"Scegli documento locale",search:"Cerca documenti",rescan:"Aggiorna elenco",navigation:"Navigazione",files:"File",outline:"Indice",documents:"Documenti",ready:"Pronto",readerSettings:"Impostazioni di lettura",readingMode:"Modalità di lettura",vertical:"Verticale",horizontal:"Orizzontale",paged:"Pagine",source:"Sorgente",media:"Media",smallerText:"Testo più piccolo",largerText:"Testo più grande",palette:"Tavolozza",language:"Lingua",darkMode:"Modalità scura",lightMode:"Modalità chiara",fullscreen:"Schermo intero",empty:"Scegli un documento per iniziare.",mediaPreview:"Anteprima media",close:"Chiudi",live:"Live",loading:"Caricamento…",loadError:"Impossibile aprire il documento.",refreshed:"Documento aggiornato",renderedView:"Anteprima",sourceView:"Testo sorgente",noOutline:"Nessun titolo nel documento.",noMedia:"Nessun media nel documento.",copy:"Copia",copied:"Copiato",invalidSource:"Inserisci un URL o percorso locale valido.",noMatches:"Nessun documento corrispondente." }
  };

  const libraryTranslations = {
    en:{libraryButton:"Library",fileButton:"File",changeLibrary:"Change library folder",noLibraryShort:"No folder selected",noLibrary:"Choose a library folder to begin.",libraryChanged:"Library folder updated",folderSelectionUnavailable:"Folder selection is available in the desktop app.",collapseSidebar:"Collapse sidebar",expandSidebar:"Expand sidebar"},
    "zh-Hant":{libraryButton:"資料夾",fileButton:"檔案",changeLibrary:"更換資料庫資料夾",noLibraryShort:"尚未選擇資料夾",noLibrary:"請先選擇要閱讀的資料夾。",libraryChanged:"資料庫資料夾已更新",folderSelectionUnavailable:"資料夾選擇功能僅在桌面 App 提供。",collapseSidebar:"收合側欄",expandSidebar:"展開側欄"},
    "zh-Hans":{libraryButton:"文件夹",fileButton:"文件",changeLibrary:"更换资料库文件夹",noLibraryShort:"尚未选择文件夹",noLibrary:"请先选择要阅读的文件夹。",libraryChanged:"资料库文件夹已更新",folderSelectionUnavailable:"文件夹选择功能仅在桌面 App 提供。",collapseSidebar:"收起侧栏",expandSidebar:"展开侧栏"},
    ja:{libraryButton:"フォルダ",fileButton:"ファイル",changeLibrary:"ライブラリフォルダを変更",noLibraryShort:"フォルダ未選択",noLibrary:"最初にライブラリフォルダを選択してください。",libraryChanged:"ライブラリを更新しました",folderSelectionUnavailable:"フォルダ選択はデスクトップアプリで利用できます。",collapseSidebar:"サイドバーを閉じる",expandSidebar:"サイドバーを開く"},
    ko:{libraryButton:"폴더",fileButton:"파일",changeLibrary:"라이브러리 폴더 변경",noLibraryShort:"선택한 폴더 없음",noLibrary:"먼저 라이브러리 폴더를 선택하세요.",libraryChanged:"라이브러리 폴더가 변경되었습니다",folderSelectionUnavailable:"폴더 선택은 데스크톱 앱에서 사용할 수 있습니다.",collapseSidebar:"사이드바 접기",expandSidebar:"사이드바 펼치기"},
    es:{libraryButton:"Carpeta",fileButton:"Archivo",changeLibrary:"Cambiar carpeta",noLibraryShort:"Sin carpeta",noLibrary:"Elige una carpeta para comenzar.",libraryChanged:"Carpeta actualizada",folderSelectionUnavailable:"La selección de carpetas está disponible en la aplicación de escritorio.",collapseSidebar:"Contraer barra lateral",expandSidebar:"Expandir barra lateral"},
    fr:{libraryButton:"Dossier",fileButton:"Fichier",changeLibrary:"Changer de dossier",noLibraryShort:"Aucun dossier",noLibrary:"Choisissez un dossier pour commencer.",libraryChanged:"Dossier mis à jour",folderSelectionUnavailable:"La sélection de dossiers est disponible dans l’application de bureau.",collapseSidebar:"Réduire la barre latérale",expandSidebar:"Développer la barre latérale"},
    de:{libraryButton:"Ordner",fileButton:"Datei",changeLibrary:"Bibliotheksordner ändern",noLibraryShort:"Kein Ordner",noLibrary:"Wähle zuerst einen Bibliotheksordner.",libraryChanged:"Bibliotheksordner aktualisiert",folderSelectionUnavailable:"Die Ordnerauswahl ist in der Desktop-App verfügbar.",collapseSidebar:"Seitenleiste einklappen",expandSidebar:"Seitenleiste ausklappen"},
    "pt-BR":{libraryButton:"Pasta",fileButton:"Arquivo",changeLibrary:"Alterar pasta",noLibraryShort:"Nenhuma pasta",noLibrary:"Escolha uma pasta para começar.",libraryChanged:"Pasta atualizada",folderSelectionUnavailable:"A seleção de pastas está disponível no aplicativo para desktop.",collapseSidebar:"Recolher barra lateral",expandSidebar:"Expandir barra lateral"},
    ru:{libraryButton:"Папка",fileButton:"Файл",changeLibrary:"Сменить папку",noLibraryShort:"Папка не выбрана",noLibrary:"Сначала выберите папку библиотеки.",libraryChanged:"Папка библиотеки обновлена",folderSelectionUnavailable:"Выбор папки доступен в настольном приложении.",collapseSidebar:"Свернуть панель",expandSidebar:"Развернуть панель"},
    it:{libraryButton:"Cartella",fileButton:"File",changeLibrary:"Cambia cartella",noLibraryShort:"Nessuna cartella",noLibrary:"Scegli una cartella per iniziare.",libraryChanged:"Cartella aggiornata",folderSelectionUnavailable:"La selezione delle cartelle è disponibile nell’app desktop.",collapseSidebar:"Comprimi barra laterale",expandSidebar:"Espandi barra laterale"}
  };

  const palettes = [
    ["dream-rose","Dream Rose","夢幻粉櫻",["#fff2f7","#c54f7e","#f6d6e3"]],
    ["lavender-mist","Lavender Mist","薰衣草霧",["#f7f2ff","#8f69c4","#e8dcf8"]],
    ["sakura-milk","Sakura Milk","櫻花牛奶",["#fff5f7","#d86f8b","#f8dce4"]],
    ["peach-dawn","Peach Dawn","蜜桃晨光",["#fff5ef","#d9785c","#f8ddcf"]],
    ["apricot-cream","Apricot Cream","杏桃奶油",["#fff8ef","#c98449","#f4e1c8"]],
    ["honey-tea","Honey Tea","蜂蜜伯爵",["#fff9e9","#b9842f","#f2e2b7"]],
    ["matcha-cloud","Matcha Cloud","抹茶雲",["#f5f8ef","#779451","#dfe9cf"]],
    ["mint-glass","Mint Glass","薄荷玻璃",["#effaf7","#3d9b83","#d2eee6"]],
    ["seafoam-pearl","Seafoam Pearl","海沫珍珠",["#effafa","#3d9495","#d4eded"]],
    ["sky-ribbon","Sky Ribbon","晴空絲帶",["#eff8ff","#4c90c8","#d7eafa"]],
    ["moonlight-blue","Moonlight Blue","月光藍",["#f1f5ff","#5b78ba","#dce5f8"]],
    ["iris-violet","Iris Violet","鳶尾紫",["#f6f1ff","#805db4","#e7daf7"]],
    ["blueberry-milk","Blueberry Milk","藍莓牛奶",["#f3f4ff","#6874be","#dfe2f8"]],
    ["grape-velvet","Grape Velvet","葡萄天鵝絨",["#faf1fb","#9b5da0","#efdaef"]],
    ["rosewood","Rosewood","玫瑰木",["#fff3f4","#aa5c69","#f0d9dd"]],
    ["cocoa-berry","Cocoa Berry","可可莓果",["#fbf5f1","#9b6a55","#eadbd3"]],
    ["champagne-gold","Champagne Gold","香檳金",["#fffaf0","#a88745","#eee3c8"]],
    ["silver-lilac","Silver Lilac","銀霧丁香",["#f7f6fa","#817893","#e5e1eb"]],
    ["aurora-teal","Aurora Teal","極光青",["#eff9f8","#2d8d8b","#d0ece9"]],
    ["ink-paper","Ink Paper","墨色紙張",["#f5f5f2","#536b78","#dce3e5"]]
  ].map(([id,name,zh,colors]) => ({id,name,zh,colors}));

  const emojiMap = { smile:"😊",heart:"❤️",sparkles:"✨",star:"⭐",warning:"⚠️",info:"ℹ️",check:"✅",x:"❌",rocket:"🚀",bulb:"💡",book:"📖",memo:"📝",fire:"🔥",tada:"🎉",eyes:"👀",wave:"👋",thumbsup:"👍",coffee:"☕" };
  const state = {
    files: [], currentPath:"", currentSource:"", currentBase:"", currentName:"", sourceType:"", rawText:"", renderText:"",
    modifiedNs:null, fontSize:Number(localStorage.getItem("lumareader-font") || localStorage.getItem("md-reader-font") || 18),
    mode:localStorage.getItem("lumareader-mode") || localStorage.getItem("md-reader-mode") || "vertical",
    language:localStorage.getItem("lumareader-language") || "en", palette:localStorage.getItem("lumareader-palette") || localStorage.getItem("md-reader-palette") || "dream-rose",
    openFolders:new Set(), view:"rendered", liveTimer:null, lastWheelAt:0, media:[], libraryRoot:null,
    sidebarCollapsed:localStorage.getItem("lumareader-sidebar-collapsed")==="true"
  };

  const $ = (selector) => document.querySelector(selector);
  const treeEl = $("#files-panel"), outlineEl = $("#outline-panel"), contentEl = $("#content"), rawEl = $("#raw-source");
  const searchEl = $("#search"), sourceInputEl = $("#source-input"), nameEl = $("#file-name"), pathEl = $("#file-path");
  const progressEl = $("#progress"), sidebarEl = $("#sidebar"), shellEl = $("#reader-shell"), pageNumberEl = $("#page-number");
  const paletteToggleEl = $("#palette-toggle"), paletteMenuEl = $("#palette-menu"), paletteNameEl = $("#palette-name");
  const languageEl = $("#language"), themeEl = $("#theme"), mediaPanelEl = $("#media-panel"), mediaGridEl = $("#media-grid"), scrimEl = $("#panel-scrim");
  const libraryRootEl = $("#library-root"), sidebarToggleEl = $("#sidebar-toggle");

  function t(key) { return libraryTranslations[state.language]?.[key] || translations[state.language]?.[key] || libraryTranslations.en[key] || translations.en[key] || key; }
  function escapeHtml(value) { return String(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;"); }
  function escapeRegExp(value) { return value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"); }
  function isDocumentHref(value) { return SUPPORTED_EXTENSIONS.some((ext) => value.toLowerCase().split(/[?#]/)[0].endsWith(ext)); }
  function paletteLabel(palette) { return state.language.startsWith("zh") ? palette.zh : palette.name; }

  function applyLanguage(language) {
    state.language = translations[language] ? language : "en";
    localStorage.setItem("lumareader-language", state.language);
    document.documentElement.lang = state.language;
    languageEl.value = state.language;
    document.querySelectorAll("[data-i18n]").forEach((el) => { el.textContent = t(el.dataset.i18n); });
    document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => { el.placeholder = t(el.dataset.i18nPlaceholder); });
    document.querySelectorAll("[data-i18n-title]").forEach((el) => { const value=t(el.dataset.i18nTitle); el.title=value; if(el.matches("button")) el.setAttribute("aria-label",value); });
    document.querySelectorAll("[data-i18n-aria]").forEach((el) => el.setAttribute("aria-label",t(el.dataset.i18nAria)));
    updateThemeButton(); renderPaletteMenu(); buildOutline(); rebuildMedia(); updateLibraryDisplay(); updateSidebarToggle();
  }

  function folderName(value){return String(value||"").split(/[\\/]/).filter(Boolean).pop()||t("noLibraryShort");}
  function updateLibraryDisplay(){libraryRootEl.textContent=state.libraryRoot?folderName(state.libraryRoot):t("noLibraryShort");libraryRootEl.title=state.libraryRoot||t("noLibraryShort");}
  function isNarrow(){return matchMedia("(max-width: 820px)").matches;}
  function updateSidebarToggle(){const collapsed=isNarrow()?!sidebarEl.classList.contains("open"):state.sidebarCollapsed;const label=t(collapsed?"expandSidebar":"collapseSidebar");sidebarToggleEl.textContent=collapsed?"☰":"‹";sidebarToggleEl.title=label;sidebarToggleEl.setAttribute("aria-label",label);sidebarToggleEl.setAttribute("aria-expanded",collapsed?"false":"true");document.body.classList.toggle("sidebar-collapsed",!isNarrow()&&state.sidebarCollapsed);}
  function toggleSidebar(){if(isNarrow()){sidebarEl.classList.toggle("open");document.body.classList.toggle("sidebar-open",sidebarEl.classList.contains("open"));}else{state.sidebarCollapsed=!state.sidebarCollapsed;localStorage.setItem("lumareader-sidebar-collapsed",String(state.sidebarCollapsed));}updateSidebarToggle();}
  function closeSidebarOnNarrow(){if(!isNarrow())return;sidebarEl.classList.remove("open");document.body.classList.remove("sidebar-open");updateSidebarToggle();}
  function showEmptyLibrary(){stopLiveRefresh();state.currentPath="";state.currentSource="";state.rawText="";state.renderText="";nameEl.textContent="Kainnne LumaReader";pathEl.textContent=t("ready");contentEl.innerHTML=`<p class="empty">${escapeHtml(t("noLibrary"))}</p>`;rawEl.querySelector("code").textContent="";buildOutline();rebuildMedia();}

  function renderPaletteMenu() {
    paletteMenuEl.innerHTML = "";
    palettes.forEach((palette) => {
      const button=document.createElement("button"); button.type="button"; button.className="palette-option"; button.setAttribute("role","menuitemradio");
      button.setAttribute("aria-checked",palette.id===state.palette?"true":"false"); button.dataset.palette=palette.id;
      const swatches=palette.colors.map((color)=>`<i style="--swatch:${color}"></i>`).join("");
      button.innerHTML=`<span class="palette-swatch">${swatches}</span><span>${escapeHtml(paletteLabel(palette))}</span><b aria-hidden="true">${palette.id===state.palette?"✓":""}</b>`;
      button.addEventListener("click",()=>{ applyPalette(palette.id,true); closePalette(); }); paletteMenuEl.appendChild(button);
    });
    const selected=palettes.find((item)=>item.id===state.palette)||palettes[0]; paletteNameEl.textContent=paletteLabel(selected);
    const swatch=$("#palette-swatch"); swatch.innerHTML=selected.colors.map((color)=>`<i style="--swatch:${color}"></i>`).join("");
  }

  function applyPalette(palette, rerender=false) {
    state.palette=palettes.some((item)=>item.id===palette)?palette:"dream-rose";
    document.documentElement.dataset.palette=state.palette; localStorage.setItem("lumareader-palette",state.palette); renderPaletteMenu();
    if(rerender&&state.renderText) renderDocument(true);
  }
  function openPalette(){ paletteMenuEl.hidden=false; paletteToggleEl.setAttribute("aria-expanded","true"); }
  function closePalette(){ paletteMenuEl.hidden=true; paletteToggleEl.setAttribute("aria-expanded","false"); }

  function updateThemeButton(){ const dark=document.documentElement.classList.contains("dark"); themeEl.textContent=dark?"☀":"◐"; themeEl.dataset.i18nTitle=dark?"lightMode":"darkMode"; themeEl.title=t(dark?"lightMode":"darkMode"); themeEl.setAttribute("aria-label",themeEl.title); themeEl.classList.toggle("active",dark); $("#highlight-light").disabled=dark; $("#highlight-dark").disabled=!dark; }
  function toggleTheme(){ const dark=document.documentElement.classList.toggle("dark"); localStorage.setItem("lumareader-theme",dark?"dark":"light"); updateThemeButton(); if(state.renderText)renderDocument(true); }

  function showToast(message){ const toast=$("#toast"); toast.textContent=message; toast.hidden=false; clearTimeout(showToast.timer); showToast.timer=setTimeout(()=>{toast.hidden=true;},2200); }
  function setLoading(loading){ document.body.classList.toggle("loading",loading); pathEl.textContent=loading?t("loading"):(state.currentPath||t("ready")); }

  function protectMath(source){ const tokens=[]; const pattern=/\$\$[\s\S]+?\$\$|\\\[[\s\S]+?\\\]|\\\([\s\S]+?\\\)|\$(?!\s)(?:\\.|[^$\n])+?\$/g; return {source:source.replace(pattern,(match)=>{const token=`LUMAMATHTOKEN${tokens.length}END`;tokens.push(match);return token;}),tokens}; }
  function protectSubscript(source){const transform=(text)=>text.replace(/(?<!~)~([^~\n]+)~(?!~)/g,(_match,value)=>`<sub>${escapeHtml(value)}</sub>`);let output="",last=0;const codePattern=/```[\s\S]*?```|~~~[\s\S]*?~~~|`[^`\n]+`/g;for(const match of source.matchAll(codePattern)){output+=transform(source.slice(last,match.index))+match[0];last=match.index+match[0].length;}return output+transform(source.slice(last));}
  function extractExtensions(source){ const abbreviations={}; const footnotes={}; const lines=source.split("\n"), kept=[]; for(let index=0;index<lines.length;index+=1){let match=/^\*\[([^\]]+)\]:\s*(.+)$/.exec(lines[index]);if(match){abbreviations[match[1]]=match[2];continue;}match=/^\[\^([^\]]+)\]:\s*(.*)$/.exec(lines[index]);if(match){const body=[match[2]];while(index+1<lines.length&&/^\s{2,}\S/.test(lines[index+1]))body.push(lines[++index].trim());footnotes[match[1]]=body.join(" ");continue;}if(/^\s*(?:import|export)\s.+from\s+["']/.test(lines[index])){kept.push(`\`${lines[index]}\``);continue;}kept.push(lines[index]);}
    let result=kept.join("\n"); Object.keys(footnotes).forEach((id)=>{const ref=new RegExp(`\\[\\^${escapeRegExp(id)}\\]`,`g`);result=result.replace(ref,`<sup class="footnote-ref"><a href="#footnote-${escapeHtml(id)}">${escapeHtml(id)}</a></sup>`);});
    const entries=Object.entries(footnotes); if(entries.length){result+=`\n\n<section class="footnotes"><hr><ol>${entries.map(([id,body])=>`<li id="footnote-${escapeHtml(id)}">${escapeHtml(body)} <a href="#">↩</a></li>`).join("")}</ol></section>`;} return {source:result,abbreviations}; }

  const allowedTags=new Set("a abbr audio blockquote br code del details div em h1 h2 h3 h4 h5 h6 hr img input kbd li mark ol p pre s section source span strong sub summary sup table tbody td th thead tr ul video".split(" "));
  const allowedAttrs=new Set("alt aria-label aria-hidden checked class colspan controls disabled href id loop muted open poster preload role rowspan src start title type".split(" "));
  function safeLink(value){ const url=String(value||"").trim(); if(!url)return""; if(/^(javascript|vbscript|data:text\/html):/i.test(url))return"#"; return url; }
  function sanitizeHtml(html){ const doc=new DOMParser().parseFromString(`<main>${html}</main>`,"text/html"),root=doc.body.firstElementChild; [...root.querySelectorAll("*")].forEach((el)=>{const tag=el.tagName.toLowerCase();if(!allowedTags.has(tag)){if(["script","style","iframe","object","embed","form"].includes(tag))el.remove();else el.replaceWith(...el.childNodes);return;}[...el.attributes].forEach((attr)=>{const name=attr.name.toLowerCase();if(name.startsWith("on")||name==="style"||!allowedAttrs.has(name))el.removeAttribute(attr.name);});if(el.hasAttribute("href"))el.setAttribute("href",safeLink(el.getAttribute("href")));if(el.hasAttribute("src"))el.setAttribute("src",safeLink(el.getAttribute("src")));if(tag==="input"){if(el.getAttribute("type")!=="checkbox"){el.remove();return;}el.setAttribute("disabled","");}});return root.innerHTML; }

  function mediaUrl(raw){ const value=String(raw||"").trim().replace(/^<|>$/g,""); if(/^(data:image\/|blob:)/i.test(value))return value;if(/^https?:/i.test(value))return value;if(state.sourceType==="remote"){try{return new URL(value,state.currentBase).href;}catch{return"";}}if(state.sourceType==="upload")return"";const query=new URLSearchParams({path:value,from:state.currentPath});return`/api/media?${query}`; }
  function rewriteMedia(root){ root.querySelectorAll("img, audio, video").forEach((el)=>{const raw=el.getAttribute("src")||"";el.dataset.originalSrc=raw;const resolved=mediaUrl(raw);if(resolved)el.setAttribute("src",resolved);else el.removeAttribute("src");el.setAttribute("loading","lazy");}); }

  function enhanceTextNodes(root,abbreviations){ const terms=Object.keys(abbreviations).sort((a,b)=>b.length-a.length);const abbrPattern=terms.length?terms.map(escapeRegExp).join("|"):"(?!)";const pattern=new RegExp(`(:[a-z0-9_+-]+:|\\^[^\\^\\n]+\\^|~[^~\\n]+~|\\b(?:${abbrPattern})\\b)`,"gi");const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach((node)=>{if(node.parentElement?.closest("pre,code,kbd,a,.katex,.mermaid,abbr,sup,sub"))return;const text=node.nodeValue;if(!pattern.test(text)){pattern.lastIndex=0;return;}pattern.lastIndex=0;const fragment=document.createDocumentFragment();let last=0;for(const match of text.matchAll(pattern)){fragment.append(text.slice(last,match.index));const token=match[0];let element=null;if(/^:[a-z0-9_+-]+:$/i.test(token)&&emojiMap[token.slice(1,-1)])fragment.append(emojiMap[token.slice(1,-1)]);else if(token.startsWith("^")&&token.endsWith("^")){element=document.createElement("sup");element.textContent=token.slice(1,-1);}else if(token.startsWith("~")&&token.endsWith("~")){element=document.createElement("sub");element.textContent=token.slice(1,-1);}else{const key=terms.find((term)=>term.toLowerCase()===token.toLowerCase());if(key){element=document.createElement("abbr");element.title=abbreviations[key];element.textContent=token;}}if(element)fragment.append(element);else if(!emojiMap[token.slice(1,-1)])fragment.append(token);last=match.index+token.length;}fragment.append(text.slice(last));node.replaceWith(fragment);}); }

  function enhanceAlerts(root){ root.querySelectorAll("blockquote").forEach((quote)=>{const first=quote.querySelector("p");if(!first)return;const match=/^\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*/i.exec(first.textContent);if(!match)return;quote.classList.add("callout",`callout-${match[1].toLowerCase()}`);first.innerHTML=first.innerHTML.replace(/^\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*/i,`<strong>${match[1]}</strong><br>`);}); }
  function slugify(text,used){const base=text.trim().toLowerCase().replace(/\s+/g,"-").replace(/[^\p{L}\p{N}_-]/gu,"")||"section";let id=base,index=2;while(used.has(id))id=`${base}-${index++}`;used.add(id);return id;}
  function buildOutline(){ outlineEl.innerHTML="";const headings=[...contentEl.querySelectorAll("h1,h2,h3,h4")];if(!headings.length){const p=document.createElement("p");p.className="sidebar-empty";p.textContent=t("noOutline");outlineEl.appendChild(p);return;}headings.forEach((heading)=>{const button=document.createElement("button");button.type="button";button.className=`outline-item level-${heading.tagName.slice(1)}`;button.textContent=heading.textContent;button.addEventListener("click",()=>{heading.scrollIntoView({behavior:"smooth",block:"start"});sidebarEl.classList.remove("open");});outlineEl.appendChild(button);});}

  async function renderDocument(preserve=false){ if(!state.renderText)return;const ratio=preserve?readingRatio():0;const extensions=extractExtensions(state.renderText);const protectedMath=protectMath(extensions.source);let html=window.marked.parse(protectSubscript(protectedMath.source),{gfm:true,breaks:false});protectedMath.tokens.forEach((math,index)=>{html=html.replaceAll(`LUMAMATHTOKEN${index}END`,escapeHtml(math));});contentEl.innerHTML=sanitizeHtml(html);const used=new Set();contentEl.querySelectorAll("h1,h2,h3,h4,h5,h6").forEach((heading)=>{heading.id=slugify(heading.textContent,used);});rewriteMedia(contentEl);enhanceAlerts(contentEl);
    if(window.renderMathInElement){try{window.renderMathInElement(contentEl,{delimiters:[{left:"$$",right:"$$",display:true},{left:"\\[",right:"\\]",display:true},{left:"\\(",right:"\\)",display:false},{left:"$",right:"$",display:false}],throwOnError:false,strict:"ignore",ignoredTags:["script","noscript","style","textarea","pre","code"]});}catch(error){console.warn("KaTeX",error);}}
    enhanceTextNodes(contentEl,extensions.abbreviations);contentEl.querySelectorAll("pre code").forEach((code)=>{if(code.classList.contains("language-mermaid")){const container=document.createElement("div");container.className="mermaid";container.textContent=code.textContent;code.parentElement.replaceWith(container);return;}try{window.hljs?.highlightElement(code);}catch{}const pre=code.closest("pre");if(pre&&!pre.querySelector(".copy-code")){const copy=document.createElement("button");copy.type="button";copy.className="copy-code";copy.textContent=t("copy");copy.addEventListener("click",async()=>{await navigator.clipboard.writeText(code.textContent);copy.textContent=t("copied");setTimeout(()=>copy.textContent=t("copy"),1200);});pre.appendChild(copy);}});
    if(window.mermaid&&contentEl.querySelector(".mermaid")){try{window.mermaid.initialize({startOnLoad:false,securityLevel:"strict",theme:document.documentElement.classList.contains("dark")?"dark":"default",fontFamily:"-apple-system, BlinkMacSystemFont, sans-serif",suppressErrorRendering:true});await window.mermaid.run({nodes:contentEl.querySelectorAll(".mermaid")});}catch(error){console.warn("Mermaid",error);}}
    rawEl.querySelector("code").textContent=state.rawText;buildOutline();rebuildMedia();requestAnimationFrame(()=>{updatePagination();if(preserve)restoreReadingRatio(ratio);}); }

  function rebuildMedia(){state.media=[...contentEl.querySelectorAll("img,audio,video")].map((el)=>({tag:el.tagName.toLowerCase(),src:el.currentSrc||el.src||"",alt:el.alt||el.title||""})).filter((item)=>item.src);mediaGridEl.innerHTML="";$("#media-count").textContent=state.media.length?` · ${state.media.length}`:"";if(!state.media.length){const p=document.createElement("p");p.className="sidebar-empty";p.textContent=t("noMedia");mediaGridEl.appendChild(p);return;}state.media.forEach((item,index)=>{const figure=document.createElement("figure");if(item.tag==="img"){const img=document.createElement("img");img.src=item.src;img.alt=item.alt;figure.appendChild(img);}else{const media=document.createElement(item.tag);media.src=item.src;media.controls=true;figure.appendChild(media);}const caption=document.createElement("figcaption");caption.textContent=item.alt||`${t("media")} ${index+1}`;figure.appendChild(caption);mediaGridEl.appendChild(figure);});}

  function treeFromFiles(files){const root={dirs:new Map(),files:[]};files.forEach((file)=>{const parts=file.path.split("/"),name=parts.pop();let node=root;parts.forEach((part)=>{if(!node.dirs.has(part))node.dirs.set(part,{dirs:new Map(),files:[]});node=node.dirs.get(part);});node.files.push({...file,displayName:name.replace(/\.(md|mkd|mdx|markdown)$/i,"")});});return root;}
  function renderTreeNode(node,container,parentPath=""){[...node.dirs.entries()].sort((a,b)=>a[0].localeCompare(b[0],state.language,{numeric:true})).forEach(([name,child])=>{const folderPath=parentPath?`${parentPath}/${name}`:name,details=document.createElement("details");details.className="folder";details.open=state.openFolders.has(folderPath);details.addEventListener("toggle",()=>details.open?state.openFolders.add(folderPath):state.openFolders.delete(folderPath));const summary=document.createElement("summary");summary.textContent=name;details.appendChild(summary);const inner=document.createElement("div");inner.className="folder-contents";renderTreeNode(child,inner,folderPath);details.appendChild(inner);container.appendChild(details);});[...node.files].sort((a,b)=>a.displayName.localeCompare(b.displayName,state.language,{numeric:true})).forEach((file)=>{const button=document.createElement("button");button.type="button";button.className="file-button";button.textContent=file.displayName;button.title=file.path;button.classList.toggle("active",file.path===state.currentPath);button.addEventListener("click",()=>openProjectFile(file.path));container.appendChild(button);});}
  function renderTree(){const query=searchEl.value.trim().toLocaleLowerCase(state.language);const visible=query?state.files.filter((file)=>file.path.toLocaleLowerCase(state.language).includes(query)):state.files;treeEl.innerHTML="";if(!visible.length){const p=document.createElement("p");p.className="sidebar-empty";p.textContent=state.libraryRoot?t("noMatches"):t("noLibrary");treeEl.appendChild(p);return;}renderTreeNode(treeFromFiles(visible),treeEl);}

  async function loadFiles(){const response=await fetch("/api/files",{cache:"no-store"}),data=await response.json();state.libraryRoot=data.root||null;state.files=data.files||[];updateLibraryDisplay();renderTree();return data;}
  async function consumePayload(data,{preserve=false}={}){if(data.error)throw new Error(data.error);state.currentPath=data.path;state.currentSource=data.path;state.currentBase=data.base||"";state.currentName=data.name;state.sourceType=data.sourceType;state.rawText=data.text||"";state.renderText=data.renderText||data.text||"";state.modifiedNs=data.modifiedNs??null;nameEl.textContent=data.name;pathEl.textContent=data.path;sourceInputEl.value=data.sourceType==="project"?"":data.path;history.replaceState(null,"",`?source=${encodeURIComponent(data.path)}`);renderTree();setView("rendered");await renderDocument(preserve);startLiveRefresh();closeSidebarOnNarrow();}
  async function openProjectFile(path,options={}){setLoading(true);try{const response=await fetch(`/api/file?path=${encodeURIComponent(path)}`,{cache:"no-store"});await consumePayload(await response.json(),options);}catch(error){showToast(`${t("loadError")} ${error.message}`);}finally{setLoading(false);}}
  async function openSource(source,options={}){source=String(source||"").trim();if(!source){showToast(t("invalidSource"));return;}setLoading(true);try{const response=await fetch(`/api/open?source=${encodeURIComponent(source)}`,{cache:"no-store"});await consumePayload(await response.json(),options);}catch(error){showToast(`${t("loadError")} ${error.message}`);}finally{setLoading(false);}}
  async function openUploadedFile(file){if(!file||!SUPPORTED_EXTENSIONS.some((ext)=>file.name.toLowerCase().endsWith(ext))){showToast(t("loadError"));return;}const text=await file.text();state.currentPath=file.name;state.currentSource="";state.currentBase="";state.currentName=file.name;state.sourceType="upload";state.rawText=text;state.renderText=text;state.modifiedNs=null;nameEl.textContent=file.name;pathEl.textContent=file.name;setView("rendered");await renderDocument(false);stopLiveRefresh();}
  async function changeLibrary(){if(!window.lumaDesktop?.chooseLibrary){showToast(t("folderSelectionUnavailable"));return;}await window.lumaDesktop.chooseLibrary();}

  function startLiveRefresh(){stopLiveRefresh();if(!["project","external"].includes(state.sourceType)||!state.currentSource)return;state.liveTimer=setInterval(async()=>{try{const response=await fetch(`/api/meta?source=${encodeURIComponent(state.currentSource)}`,{cache:"no-store"});if(!response.ok)return;const data=await response.json();if(data.modifiedNs&&state.modifiedNs&&data.modifiedNs!==state.modifiedNs){if(state.sourceType==="project")await openProjectFile(state.currentSource,{preserve:true});else await openSource(state.currentSource,{preserve:true});showToast(t("refreshed"));}}catch{}},1500);}
  function stopLiveRefresh(){if(state.liveTimer)clearInterval(state.liveTimer);state.liveTimer=null;}

  function applyFontSize(){state.fontSize=Math.max(14,Math.min(28,state.fontSize));document.documentElement.style.setProperty("--reader-size",`${state.fontSize}px`);localStorage.setItem("lumareader-font",String(state.fontSize));requestAnimationFrame(updatePagination);}
  function setMode(mode){if(!["vertical","horizontal","paged"].includes(mode))return;state.mode=mode;localStorage.setItem("lumareader-mode",mode);shellEl.dataset.mode=mode;document.querySelectorAll(".mode-button").forEach((button)=>{const active=button.dataset.mode===mode;button.classList.toggle("active",active);button.setAttribute("aria-pressed",active?"true":"false");});contentEl.scrollLeft=0;window.scrollTo({top:0,behavior:"auto"});requestAnimationFrame(updatePagination);}
  function setView(view){state.view=view;const source=view==="source";contentEl.hidden=source;rawEl.hidden=!source;shellEl.dataset.view=source?"source":"rendered";$("#source-view").classList.toggle("active",source);$("#source-view").title=t(source?"renderedView":"sourceView");requestAnimationFrame(updatePagination);}
  function readingRatio(){if(state.mode==="vertical"){const max=document.documentElement.scrollHeight-innerHeight;return max>0?scrollY/max:0;}const target=state.view==="source"?rawEl:contentEl,max=target.scrollWidth-target.clientWidth;return max>0?target.scrollLeft/max:0;}
  function restoreReadingRatio(ratio){if(state.mode==="vertical"){const max=document.documentElement.scrollHeight-innerHeight;window.scrollTo({top:max*ratio,behavior:"auto"});}else{const target=state.view==="source"?rawEl:contentEl,max=target.scrollWidth-target.clientWidth;target.scrollLeft=max*ratio;}updatePagination();}
  function updateProgress(){const ratio=readingRatio();progressEl.style.width=`${Math.max(0,Math.min(100,ratio*100))}%`;}
  function updatePagination(){const paged=state.mode==="paged",target=state.view==="source"?rawEl:contentEl;pageNumberEl.classList.toggle("visible",paged);if(!paged){pageNumberEl.textContent="";updateProgress();return;}const width=Math.max(1,target.clientWidth),total=Math.max(1,Math.ceil(target.scrollWidth/width)),current=Math.min(total,Math.max(1,Math.round(target.scrollLeft/width)+1));pageNumberEl.textContent=`${current} / ${total}`;updateProgress();}
  function moveReading(direction){if(state.mode==="vertical")return;const target=state.view==="source"?rawEl:contentEl,step=state.mode==="paged"?target.clientWidth:Math.max(360,target.clientWidth*.78);target.scrollBy({left:direction*step,behavior:"smooth"});setTimeout(updatePagination,260);}

  function openMediaPanel(){mediaPanelEl.classList.add("open");mediaPanelEl.setAttribute("aria-hidden","false");scrimEl.hidden=false;}
  function closeMediaPanel(){mediaPanelEl.classList.remove("open");mediaPanelEl.setAttribute("aria-hidden","true");scrimEl.hidden=true;}
  function switchSidebarPanel(panelId){document.querySelectorAll(".sidebar-tab").forEach((tab)=>{const active=tab.dataset.panel===panelId;tab.classList.toggle("active",active);tab.setAttribute("aria-selected",active?"true":"false");});document.querySelectorAll(".sidebar-panel").forEach((panel)=>panel.hidden=panel.id!==panelId);}

  contentEl.addEventListener("click",(event)=>{const link=event.target.closest("a");if(!link)return;const href=link.getAttribute("href")||"";if(!href)return;if(href.startsWith("#")){event.preventDefault();contentEl.querySelector(href)?.scrollIntoView({behavior:"smooth"});return;}if(href.startsWith("file://")||(/^https?:/i.test(href)&&isDocumentHref(href))){event.preventDefault();openSource(href);return;}if(isDocumentHref(href)){event.preventDefault();if(state.sourceType==="remote"){openSource(new URL(href,state.currentBase).href);return;}if(state.sourceType==="external"){const base=new URL(state.currentBase);openSource(new URL(href,base).href);return;}const parts=state.currentPath.split("/");parts.pop();href.split(/[?#]/)[0].split("/").forEach((part)=>{if(!part||part===".")return;if(part==="..")parts.pop();else parts.push(decodeURIComponent(part));});const target=parts.join("/");if(state.files.some((file)=>file.path===target))openProjectFile(target);}});

  paletteToggleEl.addEventListener("click",()=>paletteMenuEl.hidden?openPalette():closePalette());
  document.addEventListener("click",(event)=>{if(!event.target.closest(".palette-control"))closePalette();});
  languageEl.addEventListener("change",()=>applyLanguage(languageEl.value)); themeEl.addEventListener("click",toggleTheme);
  searchEl.addEventListener("input",renderTree);$("#refresh").addEventListener("click",async()=>{await loadFiles();showToast(t("refreshed"));});
  $("#open-source").addEventListener("click",()=>openSource(sourceInputEl.value));sourceInputEl.addEventListener("keydown",(event)=>{if(event.key==="Enter")openSource(sourceInputEl.value);});
  $("#change-library").addEventListener("click",changeLibrary);
  $("#choose-file").addEventListener("click",()=>$("#file-picker").click());$("#file-picker").addEventListener("change",(event)=>openUploadedFile(event.target.files?.[0]));
  $("#font-down").addEventListener("click",()=>{state.fontSize-=1;applyFontSize();});$("#font-up").addEventListener("click",()=>{state.fontSize+=1;applyFontSize();});
  $("#source-view").addEventListener("click",()=>setView(state.view==="source"?"rendered":"source"));$("#media-view").addEventListener("click",openMediaPanel);$("#media-close").addEventListener("click",closeMediaPanel);scrimEl.addEventListener("click",closeMediaPanel);
  document.querySelectorAll(".mode-button").forEach((button)=>button.addEventListener("click",()=>setMode(button.dataset.mode)));document.querySelectorAll(".sidebar-tab").forEach((button)=>button.addEventListener("click",()=>switchSidebarPanel(button.dataset.panel)));
  sidebarToggleEl.addEventListener("click",toggleSidebar);
  window.addEventListener("scroll",updateProgress,{passive:true});window.addEventListener("resize",()=>{sidebarEl.classList.remove("open");document.body.classList.remove("sidebar-open");updateSidebarToggle();requestAnimationFrame(updatePagination);});contentEl.addEventListener("scroll",updatePagination,{passive:true});rawEl.addEventListener("scroll",updatePagination,{passive:true});
  [contentEl,rawEl].forEach((target)=>target.addEventListener("wheel",(event)=>{if(state.mode==="vertical")return;event.preventDefault();if(state.mode==="horizontal"){target.scrollBy({left:event.deltaY+event.deltaX,behavior:"auto"});return;}const now=Date.now();if(now-state.lastWheelAt<420||Math.abs(event.deltaY)+Math.abs(event.deltaX)<12)return;state.lastWheelAt=now;moveReading(event.deltaY+event.deltaX>0?1:-1);},{passive:false}));

  document.addEventListener("keydown",(event)=>{const target=event.target,key=event.key.toLowerCase(),command=event.metaKey||event.ctrlKey;if(target instanceof HTMLInputElement||target instanceof HTMLTextAreaElement||target?.isContentEditable){if(event.key==="Escape")target.blur();return;}if(command&&event.shiftKey&&key==="o"){event.preventDefault();changeLibrary();}else if(command&&key==="o"){event.preventDefault();$("#file-picker").click();}else if(command&&key==="l"){event.preventDefault();sourceInputEl.focus();}else if(command&&event.shiftKey&&key==="s"){event.preventDefault();setView(state.view==="source"?"rendered":"source");}else if(command&&event.shiftKey&&key==="m"){event.preventDefault();openMediaPanel();}else if(command&&event.shiftKey&&key==="p"){event.preventDefault();openPalette();}else if(event.key==="Escape"){closePalette();closeMediaPanel();closeSidebarOnNarrow();}else if(key==="/" ){event.preventDefault();searchEl.focus();}else if(key==="d"){event.preventDefault();toggleTheme();}else if(["-","["].includes(key)){state.fontSize-=1;applyFontSize();}else if(["+","=","]"].includes(key)){state.fontSize+=1;applyFontSize();}else if(["1","2","3"].includes(key)){setMode({1:"vertical",2:"horizontal",3:"paged"}[key]);}else if(event.key==="ArrowLeft"&&state.mode!=="vertical"){event.preventDefault();moveReading(-1);}else if(event.key==="ArrowRight"&&state.mode!=="vertical"){event.preventDefault();moveReading(1);}});

  async function initialize(){if(localStorage.getItem("lumareader-theme")==="dark"||(!localStorage.getItem("lumareader-theme")&&matchMedia("(prefers-color-scheme: dark)").matches))document.documentElement.classList.add("dark");applyPalette(state.palette);applyLanguage(state.language);updateThemeButton();applyFontSize();setMode(state.mode);updateSidebarToggle();window.lumaDesktop?.onLibraryChanged(async(payload)=>{state.libraryRoot=payload.root||null;state.openFolders.clear();showEmptyLibrary();await loadFiles();const first=state.files[0];if(first)await openProjectFile(first.path);showToast(t("libraryChanged"));});await loadFiles();const params=new URLSearchParams(location.search),requested=params.get("source")||params.get("url")||params.get("file");if(requested){if(state.files.some((file)=>file.path===requested))await openProjectFile(requested);else await openSource(requested);return;}const preferred=state.files.find((file)=>file.path.endsWith("docs/story-review/00-閱讀順序與驗收範圍.md"))||state.files[0];if(preferred)await openProjectFile(preferred.path);else showEmptyLibrary();}
  initialize().catch((error)=>{contentEl.innerHTML=`<p class="error">${escapeHtml(error.message||error)}</p>`;});
})();
