(function(){
  'use strict';
  // Functional text only; no browser locale guessing or persisted suppression.
  const copy={
    en:['Switch to dark mode?','Dark mode may make code easier to read. You can return to light mode in Settings.','Not now','Switch to dark mode','Do not show again','Unsaved changes','Save changes before switching or closing this document?','Cancel','Discard','Save','Close','Open documents'],
    'zh-Hant':['切換深色模式？','深色模式可能更適合閱讀程式碼。之後可在「設定」切回明亮模式。','暫時不用','切換深色模式','不再顯示','尚未儲存變更','切換或關閉這份文件前，要先儲存變更嗎？','取消','捨棄變更','儲存','關閉','已開啟的文件'],
    'zh-Hans':['切换深色模式？','深色模式可能更适合阅读代码。之后可在“设置”切回浅色模式。','暂时不用','切换深色模式','不再显示','更改尚未保存','切换或关闭此文档前，要保存更改吗？','取消','放弃更改','保存','关闭','已打开的文档'],
    ja:['ダークモードに切り替えますか？','コードが読みやすくなる場合があります。「設定」でライトモードに戻せます。','今はしない','ダークモードに切り替え','今後表示しない','未保存の変更','文書を切り替える、または閉じる前に変更を保存しますか？','キャンセル','変更を破棄','保存','閉じる','開いている文書'],
    ko:['다크 모드로 전환할까요?','코드를 읽기 더 편할 수 있습니다. 설정에서 라이트 모드로 돌아갈 수 있습니다.','나중에','다크 모드로 전환','다시 표시하지 않음','저장하지 않은 변경','문서를 전환하거나 닫기 전에 변경 사항을 저장할까요?','취소','변경 버리기','저장','닫기','열린 문서'],
    es:['¿Cambiar al modo oscuro?','Puede facilitar la lectura de código. Puedes volver al modo claro en Ajustes.','Ahora no','Cambiar al modo oscuro','No volver a mostrar','Cambios sin guardar','¿Guardar los cambios antes de cambiar o cerrar este documento?','Cancelar','Descartar','Guardar','Cerrar','Documentos abiertos'],
    fr:['Passer en mode sombre ?','Cela peut faciliter la lecture du code. Vous pouvez revenir au mode clair dans les réglages.','Pas maintenant','Passer en mode sombre','Ne plus afficher','Modifications non enregistrées','Enregistrer avant de changer ou de fermer ce document ?','Annuler','Abandonner','Enregistrer','Fermer','Documents ouverts'],
    de:['Zum Dunkelmodus wechseln?','Code kann dadurch leichter lesbar sein. In den Einstellungen lässt sich der Hellmodus wieder aktivieren.','Nicht jetzt','Zum Dunkelmodus wechseln','Nicht erneut anzeigen','Ungespeicherte Änderungen','Änderungen vor dem Wechseln oder Schließen dieses Dokuments speichern?','Abbrechen','Verwerfen','Speichern','Schließen','Geöffnete Dokumente'],
    'pt-BR':['Mudar para o modo escuro?','Pode facilitar a leitura de código. Volte ao modo claro em Configurações.','Agora não','Mudar para o modo escuro','Não mostrar novamente','Alterações não salvas','Salvar antes de trocar ou fechar este documento?','Cancelar','Descartar','Salvar','Fechar','Documentos abertos'],
    ru:['Перейти в тёмный режим?','Код может стать удобнее для чтения. Вернуть светлый режим можно в настройках.','Не сейчас','Перейти в тёмный режим','Больше не показывать','Несохранённые изменения','Сохранить изменения перед переходом или закрытием документа?','Отмена','Отменить изменения','Сохранить','Закрыть','Открытые документы'],
    it:['Passare alla modalità scura?','Può facilitare la lettura del codice. Puoi tornare alla modalità chiara nelle impostazioni.','Non ora','Passa alla modalità scura','Non mostrare più','Modifiche non salvate','Salvare prima di cambiare o chiudere questo documento?','Annulla','Scarta','Salva','Chiudi','Documenti aperti']
  };
  function dialog(language,dark){
    const c=copy[language]||copy.en,el=document.createElement('dialog');el.className='report-delete-dialog desktop-confirm-dialog '+(dark?'code-dark-dialog':'document-switch-dialog');
    const heading=document.createElement('h3');heading.id=dark?'code-dark-title':'document-switch-title';heading.textContent=c[dark?0:5];el.setAttribute('aria-labelledby',heading.id);
    const description=document.createElement('p');description.textContent=c[dark?1:6];el.append(heading,description);
    let checkbox;if(dark){const label=document.createElement('label');label.className='report-dismiss';checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.dataset.promptHide='';const span=document.createElement('span');span.textContent=c[4];label.append(checkbox,span);el.append(label);}
    const footer=document.createElement('footer');for(const [value,index]of dark?[['cancel',2],['accept',3]]:[['cancel',7],['discard',8],['save',9]]){const button=document.createElement('button');button.type='button';button.dataset.choice=value;button.textContent=c[index];button.onclick=()=>el.close(value);footer.append(button);}el.append(footer);document.body.append(el);
    const result=new Promise(resolve=>el.addEventListener('close',()=>{const value=el.returnValue;const suppressed=checkbox?.checked===true;el.remove();resolve(dark?{accepted:value==='accept',suppress:suppressed}:['save','discard'].includes(value)?value:'cancel');},{once:true}));el.showModal();footer.firstElementChild.focus();return result;
  }
  function createTabs(shell,actions){
    const nav=document.createElement('nav');nav.id='document-tabs';nav.className='document-tabs';nav.hidden=true;nav.setAttribute('role','tablist');shell.querySelector('.reader-bar').after(nav);
    let dragging=null,suppressClickUntil=0;
    const available=()=>!nav.hidden&&actions.canReorder?.()!==false;
    const clearTargets=()=>nav.querySelectorAll('[data-tab-drop]').forEach(el=>delete el.dataset.tabDrop);
    const clearDrag=()=>{dragging=null;clearTargets();nav.querySelectorAll('.is-dragging').forEach(el=>el.classList.remove('is-dragging'));};
    const destination=event=>{const item=event.target.closest('.document-tab');if(!item||!nav.contains(item)||item.dataset.tabKey===dragging)return null;const r=item.getBoundingClientRect();return{key:item.dataset.tabKey,after:event.clientX>=r.left+r.width/2,item};};
    nav.ondragstart=event=>{const item=event.target.closest('.document-tab');if(!item||event.target.closest('.document-tab-close')||!available()){event.preventDefault();return;}dragging=item.dataset.tabKey;item.classList.add('is-dragging');event.dataTransfer.setData('application/x-luma-document-tab',dragging);event.dataTransfer.effectAllowed='move';event.stopPropagation();};
    nav.ondragover=event=>{if(!dragging||!available())return;event.preventDefault();event.stopPropagation();event.dataTransfer.dropEffect='move';clearTargets();const target=destination(event);if(target)target.item.dataset.tabDrop=target.after?'after':'before';const r=nav.getBoundingClientRect();if(event.clientX<r.left+30)nav.scrollLeft-=12;else if(event.clientX>r.right-30)nav.scrollLeft+=12;};
    nav.ondrop=event=>{if(!dragging)return;event.preventDefault();event.stopPropagation();const source=dragging,target=available()?destination(event):null;clearDrag();suppressClickUntil=Date.now()+300;if(target)actions.reorder?.(source,target.key,target.after);};
    nav.ondragend=()=>{if(dragging)suppressClickUntil=Date.now()+300;clearDrag();};
    const observer=new ResizeObserver(()=>shell.style.setProperty('--reader-toolbar-height',shell.querySelector('.reader-bar').getBoundingClientRect().height+'px'));observer.observe(shell.querySelector('.reader-bar'));
    return{render(tabs,active,dirty,language,{hidden=false}={}){const c=copy[language]||copy.en;nav.setAttribute('aria-label',c[11]);const scroll=nav.scrollLeft,focused=document.activeElement?.dataset.tabKey;clearDrag();nav.replaceChildren();nav.hidden=hidden||tabs.length===0;document.body.classList.toggle('has-document-tabs',!hidden&&tabs.length>0);
      for(const tab of tabs){const item=document.createElement('div');item.className='document-tab'+(tab.key===active?' is-active':'');item.dataset.tabKey=tab.key;item.draggable=!hidden;const select=document.createElement('button');select.type='button';select.className='document-tab-select';select.dataset.tabKey=tab.key;select.setAttribute('role','tab');select.setAttribute('aria-selected',String(tab.key===active));select.tabIndex=tab.key===active?0:-1;select.title=tab.path;select.textContent=tab.name;if(tab.key===active&&dirty){const dot=document.createElement('span');dot.className='document-tab-dirty';dot.textContent='•';dot.setAttribute('aria-label',c[5]);select.append(dot);}select.onclick=()=>{if(Date.now()>=suppressClickUntil)actions.select(tab.key);};
        select.onkeydown=event=>{const current=tabs.findIndex(t=>t.key===tab.key);let next;if(event.key==='ArrowRight')next=(current+1)%tabs.length;if(event.key==='ArrowLeft')next=(current+tabs.length-1)%tabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=tabs.length-1;if(next!==undefined){event.preventDefault();actions.select(tabs[next].key);}if(event.key==='Delete'){event.preventDefault();actions.close(tab.key);}};
        const close=document.createElement('button');close.type='button';close.className='document-tab-close';close.textContent='×';close.title=c[10];close.setAttribute('aria-label',c[10]+' '+tab.name);close.onclick=()=>actions.close(tab.key);item.append(select,close);nav.append(item);
      }nav.scrollLeft=scroll;const current=[...nav.querySelectorAll('[role=tab]')].find(el=>el.dataset.tabKey===active);if(focused)current?.focus({preventScroll:true});const item=current?.parentElement;if(item){const r=item.getBoundingClientRect(),n=nav.getBoundingClientRect();if(r.left<n.left)nav.scrollLeft-=n.left-r.left;if(r.right>n.right)nav.scrollLeft+=r.right-n.right;}
    }};
  }
  window.LumaDesktopUI={createTabs,offerDarkMode:language=>dialog(language,true),confirmNavigation:language=>dialog(language,false)};
})();
