'use strict';
const http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');const {chromium}=require('playwright-core');
async function main(){
 const root=path.resolve('site'),backendRoot=await fs.mkdtemp('/private/tmp/luma-embed-backend-');let origin;
 const server=http.createServer(async(req,res)=>{try{res.setHeader('Access-Control-Allow-Origin','*');let file=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(!file.startsWith(root+path.sep))throw Error();if((await fs.stat(file)).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.woff2':'font/woff2'})[path.extname(file)]||'application/octet-stream');res.end(await fs.readFile(file));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;
 const host=http.createServer(async(req,res)=>{if(req.method==='POST'&&req.url==='/save'){try{const chunks=[];for await(const chunk of req)chunks.push(chunk);const payload=JSON.parse(Buffer.concat(chunks));await fs.writeFile(path.join(backendRoot,'snapshot.json'),JSON.stringify(payload.document));for(const asset of payload.attachments||[])await fs.writeFile(path.join(backendRoot,asset.id+'.png'),Buffer.from(asset.bytes));res.end('ok');}catch{res.writeHead(500);res.end('failed');}return;}res.setHeader('Content-Type','text/html; charset=utf-8');res.end(`<!doctype html><style>body{margin:0}#reader{height:90dvh}</style><button id="external">外部選圖</button><div id="reader"></div><script type="module">import {mountLumaReader} from '${origin}/embed/lumareader.js';window.mount=async(options={})=>{if(window.editor)await editor.destroy({discardChanges:true});window.failSave=false;window.events=[];window.selection=null;window.editor=mountLumaReader(document.querySelector('#reader'),{document:{id:'test',title:'註記稿',markdown:'相同句子😀 第一段\\n\\n相同句子😀 第二段\\n'},language:'zh-Hant',features:{annotations:true},selectionActions:[{id:'image',label:'加入圖片',icon:'image'},{id:'emphasis',label:'強調重點',icon:'highlight'}],onAction:value=>window.action=value,onSelectionChange:value=>window.selection=value,onAnnotationsChange:value=>events.push(value),onSave:async d=>{if(failSave)throw Error('save failed');const attachments=[];for(const note of d.annotations?.items||[]){if(note.asset?.local){const a=await editor.getAttachment(note.asset.id);attachments.push({...a,bytes:[...a.bytes]});}}const r=await fetch('/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document:d,attachments})});if(!r.ok)throw Error('backend save failed');window.saved=d;},...options});await editor.ready;};window.ready=true;</script>`);});await new Promise(r=>host.listen(0,'127.0.0.1',r));
 let browser;try{browser=await chromium.launch({headless:true,executablePath:process.env.LUMA_CHROMIUM_EXECUTABLE});const page=await browser.newPage({viewport:{width:1440,height:900},hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(15000);await page.goto(`http://127.0.0.1:${host.address().port}`);await page.waitForFunction(()=>window.ready);await page.evaluate(()=>mount());const frame=page.frameLocator('iframe');await frame.locator('.direct-prose').waitFor();
 // Real DOM selection in the second occurrence. Parent never reads the iframe DOM in production.
 async function selectParagraph(index,start,end){const target=frame.locator('.direct-prose > p').nth(index),box=await target.boundingBox();await target.click({position:{x:box.width-2,y:box.height/2}});await frame.locator('.direct-prose > p').nth(index).evaluate(async(p,{start,end})=>{p.closest('[contenteditable]').focus();await new Promise(r=>setTimeout(r,50));const walker=document.createTreeWalker(p,NodeFilter.SHOW_TEXT);let node,offset=0,first,last;while(node=walker.nextNode()){if(!first&&start<=offset+node.length)first=[node,start-offset];if(end<=offset+node.length){last=[node,end-offset];break;}offset+=node.length;}const range=document.createRange();range.setStart(...first);range.setEnd(...last);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);document.dispatchEvent(new Event('selectionchange'));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));},{start,end});return page.evaluate(()=>editor.getSelection());}

 let s=await selectParagraph(1,0,6);assert.equal(s.selectedText,'相同句子😀');assert.deepEqual(s.sourceRanges,[{from:12,to:18}]);await page.locator('#external').click();await page.evaluate(()=>editor.expand());await page.evaluate(()=>editor.collapse());
 const first=await page.evaluate(s=>editor.addAnnotation({...s,expectedRevision:s.revision,annotation:{id:'second',kind:'attachment',label:'第二句配圖',asset:{id:'asset-123'}}}),s);assert.equal(first.annotation.anchor.quote,s.selectedText);assert.equal(await frame.locator('.direct-prose .luma-annotation-mark').count(),1);assert.match(await frame.locator('.direct-prose > p').nth(1).innerHTML(),/data-luma-annotation/);assert.doesNotMatch(await frame.locator('.direct-prose > p').first().innerHTML(),/data-luma-annotation/);
 // Insert before the anchor, then edit inside it; native history must restore both.
 await selectParagraph(0,0,0);await page.keyboard.insertText('新增 ');let a=await page.evaluate(()=>editor.getAnnotations());assert.equal(a.annotations.items[0].status,'active',JSON.stringify({a,doc:await page.evaluate(()=>editor.getDocument())}));assert.equal(a.annotations.items[0].anchor.from,16,JSON.stringify({a,doc:await page.evaluate(()=>editor.getDocument())}));
 const stale=await page.evaluate(s=>editor.addAnnotation({...s,expectedRevision:s.revision,annotation:{id:'late',kind:'highlight'}}).then(()=>'',e=>e.code),s);assert.equal(stale,'STALE_REVISION');
 await frame.locator('.direct-prose').press('ControlOrMeta+z');a=await page.evaluate(()=>editor.getAnnotations());assert.equal(a.annotations.items[0].anchor.from,13);
 // Select within the marked text without clicking its note decoration.
 await selectParagraph(1,0,6);await page.keyboard.insertText('替換原文');a=await page.evaluate(()=>editor.getAnnotations());assert.equal(a.annotations.items[0].status,'needsReview');
 await frame.locator('.direct-prose').press('ControlOrMeta+z');a=await page.evaluate(()=>editor.getAnnotations());assert.equal(a.annotations.items[0].status,'active');
 await selectParagraph(1,0,6);await page.keyboard.press('Backspace');a=await page.evaluate(()=>editor.getAnnotations());assert.equal(a.annotations.items[0].status,'orphaned');await frame.locator('.direct-prose').press('ControlOrMeta+z');a=await page.evaluate(()=>editor.getAnnotations());assert.equal(a.annotations.items[0].status,'active');
 // Save failure preserves both; successful snapshot survives remount and iframe reload.
 await page.evaluate(()=>window.failSave=true);assert.equal(await page.evaluate(()=>editor.save().then(()=>'',e=>e.message)),'save failed');assert.equal((await page.evaluate(()=>editor.getAnnotations())).annotations.items.length,1);assert.match(await page.evaluate(()=>editor.destroy().then(()=>'',e=>e.message)),/Unsaved/);
 await page.evaluate(()=>window.failSave=false);const saved=await page.evaluate(()=>editor.save());assert.equal(saved.annotations.items.length,1);assert.equal(saved.files[0].annotations.items.length,1);assert.ok(!saved.markdown.includes('asset-123'));await page.evaluate(document=>mount({document}),saved);await frame.locator('.direct-prose .luma-annotation-mark').waitFor();await frame.locator('body').evaluate(()=>location.reload());await frame.locator('.direct-prose .luma-annotation-mark').waitFor();
 // Read-only text still allows annotations. Annotation-only read-only is separate.
 await page.evaluate(document=>mount({document,readOnly:true}),saved);await frame.locator('.direct-prose[contenteditable=false]').waitFor();s=await selectParagraph(0,0,4);const added=await page.evaluate(s=>editor.addAnnotation({...s,expectedRevision:s.revision,annotation:{id:'readonly-note',kind:'comment',body:'正文唯讀的筆記'}}),s);assert.equal(added.annotation.kind,'comment');const immutable=(await page.evaluate(()=>editor.getDocument())).markdown;await frame.locator('.direct-prose').press('ControlOrMeta+b');assert.equal((await page.evaluate(()=>editor.getDocument())).markdown,immutable);
 await page.evaluate(document=>mount({document,annotationReadOnly:true}),saved);await frame.locator('.direct-prose .luma-annotation-mark').waitFor();s=await selectParagraph(0,0,4);assert.equal(await page.evaluate(s=>editor.addAnnotation({...s,expectedRevision:s.revision,annotation:{kind:'highlight'}}).then(()=>'',e=>e.code),s),'ANNOTATIONS_READ_ONLY');
 // Updating/deleting APIs and switching files must never accept a stale target.
 await page.evaluate(document=>mount({document}),saved);await frame.locator('.direct-prose .luma-annotation-mark').waitFor();let context=await page.evaluate(()=>editor.getAnnotations());
 await page.evaluate(c=>editor.updateAnnotation({...c,expectedRevision:c.revision,annotationId:'second',patch:{label:'更新圖片標籤'}}),context);
 context=await page.evaluate(()=>editor.getAnnotations());assert.equal(context.annotations.items[0].label,'更新圖片標籤');
 await frame.locator('#file-picker').setInputFiles({name:'另一稿.md',mimeType:'text/markdown',buffer:Buffer.from('相同句子😀 另一份文件')});await frame.locator('#file-name').filter({hasText:'另一稿.md'}).waitFor();
 assert.equal((await page.evaluate(()=>editor.getAnnotations())).annotations.items.length,0);
 assert.equal(await page.evaluate(c=>editor.updateAnnotation({...c,expectedRevision:c.revision,annotationId:'second',patch:{asset:{id:'late-image'}}}).then(()=>'',e=>e.code),context),'DOCUMENT_MISMATCH');
 await frame.locator('#sidebar-toggle').click();await frame.locator('.file-button').filter({hasText:'註記稿.md'}).click();await frame.locator('.direct-prose .luma-annotation-mark').waitFor();assert.equal((await page.evaluate(()=>editor.getActiveDocument())).annotations.items[0].label,'更新圖片標籤');
 context=await page.evaluate(()=>editor.getAnnotations());await page.evaluate(c=>editor.setAnnotations({...c,expectedRevision:c.revision,annotations:c.annotations}),context);
 context=await page.evaluate(()=>editor.getAnnotations());await page.evaluate(c=>editor.deleteAnnotation({...c,expectedRevision:c.revision,annotationId:'second'}),context);assert.equal(await frame.locator('.direct-prose .luma-annotation-mark').count(),0);await frame.locator('.direct-prose').press('ControlOrMeta+z');await frame.locator('.direct-prose .luma-annotation-mark').waitFor();
 // Native actions, touch layouts, click notes and empty default UI remain compatible.
 await page.evaluate(()=>mount());await frame.locator('.direct-prose').waitFor();for(const width of [1440,768,390]){await page.setViewportSize({width,height:900});s=await selectParagraph(0,0,4);await page.evaluate(()=>window.action=null);await frame.locator('.luma-selection-actions button').first().tap();await page.waitForFunction(()=>window.action?.actionId==='image');assert.equal((await page.evaluate(()=>window.action)).actionId,'image');assert.equal((await page.evaluate(()=>action)).selection.selectionToken,s.selectionToken);assert.ok(await frame.locator('.luma-selection-actions').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;}));}
 await page.screenshot({path:'/private/tmp/luma-annotations-mobile.png'});
 await page.evaluate(()=>mount({selectionActions:undefined}));await frame.locator('.direct-prose').waitFor();await selectParagraph(0,0,4);await frame.locator('.luma-selection-actions button').nth(1).tap();await frame.locator('.luma-annotation-dialog textarea').fill('這是一則閱讀筆記');await frame.locator('.luma-annotation-dialog button').last().click();await frame.locator('.direct-prose .luma-annotation-mark').click();await frame.locator('.luma-annotation-dialog').filter({hasText:'這是一則閱讀筆記'}).waitFor();
 await frame.locator('.luma-annotation-dialog button').first().click();
 const originalImageText=(await page.evaluate(()=>editor.getDocument())).markdown;
 await selectParagraph(1,0,4);await frame.locator('.luma-selection-actions button').nth(2).click();
 const png=await fs.readFile('build/preview.png');await frame.locator('.luma-annotation-dialog input[type=file]').setInputFiles({name:'image.png',mimeType:'image/png',buffer:png});await frame.locator('.direct-prose .luma-annotation-mark.attachment').waitFor();
 const assetContext=await page.evaluate(()=>editor.getAnnotations()),assetId=assetContext.annotations.items.find(a=>a.kind==='attachment').asset.id;
 const attachment=await page.evaluate(async id=>{const a=await editor.getAttachment(id);return {...a,bytes:[...a.bytes]};},assetId);assert.deepEqual(Buffer.from(attachment.bytes),png);assert.equal((await page.evaluate(()=>editor.getDocument())).markdown,originalImageText);
 await page.evaluate(()=>editor.save());assert.equal(JSON.parse(await fs.readFile(path.join(backendRoot,'snapshot.json'),'utf8')).markdown,originalImageText);assert.deepEqual(await fs.readFile(path.join(backendRoot,assetId+'.png')),png);await frame.locator('body').evaluate(()=>location.reload());await frame.locator('.direct-prose .luma-annotation-mark.attachment').hover();await frame.locator('.luma-annotation-popover:not([hidden]) img').waitFor();assert.equal(await page.evaluate(()=>editor.getAttachment('not-in-this-document').then(()=>'',e=>e.code)),'ATTACHMENT_NOT_FOUND');
 await frame.locator('#sidebar-toggle').click();await frame.locator('#palette-toggle').click();await frame.locator('#cancel-edit').click();await frame.locator('#content .luma-annotation-mark.attachment').waitFor();
 // Public example uses the same native reader and stores a complete JSON draft.
 await page.goto(origin+'/embed/annotations.html');await frame.locator('.direct-prose').waitFor();await frame.locator('#boot-loader').waitFor({state:'hidden'});
 const paragraph=frame.locator('.direct-prose > p').first();await paragraph.click({clickCount:3});await frame.locator('.luma-selection-actions button').first().click();await frame.locator('.direct-prose .luma-annotation-mark').waitFor();await frame.locator('#edit-document').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('已存'));
 await page.reload();await frame.locator('.direct-prose .luma-annotation-mark').waitFor();await frame.locator('#boot-loader').waitFor({state:'hidden'});await page.screenshot({path:'/private/tmp/luma-annotations-example-mobile.png'});
 assert.deepEqual(errors,[]);console.log('PASS: exact duplicate/CJK/emoji selection; host bookmarks; anchors, edits/deletion/undo; stale requests; atomic saves/failure/remount/reload; text versus annotation permissions; native/touch actions and notes.');
 }finally{await browser?.close();await Promise.all([server,host].map(s=>new Promise(r=>s.close(r))));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
