'use strict';
const http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('playwright-core');const root=path.resolve('site');
function server(){return http.createServer(async(req,res)=>{try{let file=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!file.startsWith(root+path.sep))throw Error('path');if((await fs.stat(file)).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.woff2':'font/woff2','.png':'image/png'})[path.extname(file)]||'application/octet-stream');res.end(await fs.readFile(file));}catch{res.writeHead(404);res.end();}});}
async function main(){
 const host=server(),embed=server();await Promise.all([host,embed].map(s=>new Promise(r=>s.listen(0,'127.0.0.1',r))));let browser;const errors=[];
 const origin=`http://127.0.0.1:${host.address().port}`,embedOrigin=`http://127.0.0.1:${embed.address().port}`;
 const preferences={language:'zh-Hant',readerDefaultsVersion:6,onboardingVersion:5,languagePromptSeen:true,sidebarCollapsed:true,palette:'dream-rose',theme:'light'};
 try {
  browser=await chromium.launch({headless:true,...(process.env.LUMA_CHROMIUM_EXECUTABLE?{executablePath:process.env.LUMA_CHROMIUM_EXECUTABLE}:{})});const context=await browser.newContext({viewport:{width:1280,height:1050}});const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
  await context.addInitScript(p=>{if(!localStorage.getItem('lumareader-web-preferences-v1'))localStorage.setItem('lumareader-web-preferences-v1',JSON.stringify(p));},preferences);
  await page.goto(origin+'/embed/demo.html');let frame=page.frameLocator('iframe');await frame.locator('#content').waitFor({state:'attached'});await frame.locator('body:not(.booting)').waitFor();assert.ok(page.frames().some(f=>f.url().includes('/web/index.html?embed=1')));
  // The same HTML, styles, language options and settings as standalone Web.
  const standalone=await context.newPage();await standalone.goto(origin+'/web/');await standalone.locator('body:not(.booting)').waitFor();
  const structure=()=>({styles:[...document.querySelectorAll('link[rel=stylesheet]')].map(n=>n.getAttribute('href')),languages:[...document.querySelectorAll('#settings-language option')].map(n=>[n.value,n.textContent]),settings:document.querySelector('#palette-menu').textContent.replace(/\s+/g,' ').trim(),insert:document.querySelector('#editor-insert-menu').textContent.replace(/\s+/g,' ').trim()});
  assert.deepEqual(await frame.locator('body').evaluate(structure),await standalone.evaluate(structure));assert.equal(await standalone.locator('.direct-prose').count(),0);await standalone.close();
  await frame.locator('.direct-prose').waitFor();await frame.locator('.direct-prose table td').first().click();await page.keyboard.press('End');await page.keyboard.insertText('・表格修改');
  await frame.locator('#show-markdown').click();assert.equal(await frame.locator('#editor-preview-toggle').isChecked(),true);let text=await frame.locator('#source-editor').inputValue();assert.match(text,/表格修改/);text+='\n\n測試草稿：切換步驟也要保留。\n';await frame.locator('#source-editor').fill(text);await frame.locator('#show-markdown').click();
  await page.locator('#expand-reader').click();await page.waitForFunction(()=>document.querySelector('#reader').getBoundingClientRect().height===1050);assert.match(await frame.locator('.direct-prose').innerText(),/測試草稿/);await page.locator('#reader > div > button').click();await page.waitForFunction(()=>document.querySelector('#reader').getBoundingClientRect().height===560);
  // Native image insertion uses the same file import path; bytes survive a remount.
  const tiny=[...Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')];
  const imported=await frame.locator('body').evaluate(async (_,bytes)=>window.lumaDesktop.importImage({path:window.LumaEmbed.managedPath,name:'test.png',bytes}),tiny);assert.equal(imported.ok,true,JSON.stringify(imported));assert.match(imported.image.markdownPath,/^data:image\/png;base64,/);
  await frame.locator('#show-markdown').click();text=await frame.locator('#source-editor').inputValue();await frame.locator('#source-editor').fill(text+'\n![持久圖片]('+imported.image.markdownPath+')\n');await frame.locator('#show-markdown').click();
  await page.screenshot({path:'/private/tmp/luma-embed-shared-desktop.png'});
  await page.locator('#next').click();await page.locator('#image-step').waitFor();assert.equal(await page.locator('iframe').count(),0);assert.match(await page.locator('#output').innerText(),/測試草稿/);
  await page.locator('#image-url').fill('https://example.invalid/image.png');await page.locator('#image-caption').fill('插圖');await page.locator('#add-image').click();await page.locator('#back').click();frame=page.frameLocator('iframe');await frame.locator('#content').waitFor({state:'attached'});await frame.locator('body:not(.booting)').waitFor();await frame.locator('.direct-prose').waitFor();await frame.locator('#show-markdown').click();assert.match(await frame.locator('#source-editor').inputValue(),/!\[插圖\]/);assert.match(await frame.locator('#source-editor').inputValue(),/data:image\/png;base64,/);
  // The existing settings change language and palette, surviving iframe remount.
  await frame.locator('#cancel-edit').click();await frame.locator('#palette-toggle').click();await frame.locator('#settings-language').selectOption('en');assert.equal(await frame.locator('#edit-document-label').innerText(),'Edit');await frame.locator('#appearance-close').click();
  await page.reload();frame=page.frameLocator('iframe');await frame.locator('#content').waitFor({state:'attached'});await frame.locator('body:not(.booting)').waitFor();assert.equal(await frame.locator('#edit-document-label').innerText(),'Save');assert.match(await frame.locator('.direct-prose').innerText(),/測試草稿/);
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/private/tmp/luma-embed-shared-mobile.png'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  // Cross-origin persistence and save failures use the original Save button/toast.
  await page.evaluate(async ({embedOrigin,preferences})=>{
   const {mountLumaReader}=await import('/embed/lumareader.js');const container=document.createElement('div');container.id='sdk-test';container.style.height='700px';document.body.append(container);
   window.changed=[];window.failSave=true;window.holdSave=false;
   window.testEditor=mountLumaReader(container,{url:embedOrigin+'/web/index.html',preferences,document:{id:'contract',title:'整合測試',markdown:'# Test\n\nOriginal\n'},onChange:d=>changed.push(d),onSave:async d=>{if(failSave)throw Error('backend unavailable');if(holdSave)await new Promise(r=>window.releaseSave=r);window.saved=d;}});await testEditor.ready;
  },{embedOrigin,preferences});
  frame=page.frameLocator('#sdk-test iframe');await frame.locator('.direct-prose').waitFor();await frame.locator('#show-markdown').click();await frame.locator('#source-editor').fill('# Changed\n\n稿件\n');
  let failure=await page.evaluate(()=>testEditor.save().then(()=>null,e=>e.message));assert.equal(failure,'backend unavailable');assert.equal(await frame.locator('#source-editor').inputValue(),'# Changed\n\n稿件\n');failure=await page.evaluate(()=>testEditor.destroy().then(()=>null,e=>e.message));assert.match(failure,/Unsaved/);
  const snapshot=await page.evaluate(()=>testEditor.getDocument());assert.equal(snapshot.markdown,'# Changed\n\n稿件\n');
  await page.evaluate(()=>{const child=document.querySelector('#sdk-test iframe');const params=new URLSearchParams(new URL(child.src).hash.slice(1));window.dispatchEvent(new MessageEvent('message',{origin:new URL(child.src).origin,source:window,data:{protocol:'lumareader-embed-v1',channel:params.get('channel'),type:'change',document:{id:'contract',markdown:'FORGED',revision:999}}}));});assert.equal((await page.evaluate(()=>testEditor.getDocument())).markdown,snapshot.markdown);
  await page.evaluate(()=>{failSave=false;holdSave=true;window.savingTest=testEditor.save();});await page.waitForFunction(()=>typeof releaseSave==='function');await frame.locator('#source-editor').fill('# Newer changes during save\n');await page.evaluate(()=>releaseSave());await page.evaluate(()=>savingTest);failure=await page.evaluate(()=>testEditor.destroy().then(()=>null,e=>e.message));assert.match(failure,/Unsaved/);
  await page.evaluate(()=>{holdSave=false;});await frame.locator('#edit-document').click();await page.waitForFunction(()=>saved?.markdown==='# Newer changes during save\n');await frame.locator('#edit-document').filter({hasText:'已儲存'}).waitFor();
  await frame.locator('#source-editor').fill('# Preserved across iframe reload\n');await page.waitForFunction(()=>changed.at(-1)?.markdown.includes('iframe reload'));await Promise.all([page.waitForEvent('framenavigated',f=>f.url().startsWith(embedOrigin)),frame.locator('body').evaluate(()=>location.reload())]);await frame.locator('#content').waitFor({state:'attached'});await frame.locator('body:not(.booting)').waitFor();assert.match(await frame.locator('#content').innerText(),/iframe reload/);await page.evaluate(()=>testEditor.save());await page.evaluate(()=>testEditor.destroy());assert.equal(await page.locator('#sdk-test iframe').count(),0);
  assert.deepEqual(errors,[]);console.log('PASS: shared Web HTML/styles/settings/languages/insert menu; direct/table/source/preview; original Save integration; expand; next-step images; drafts; settings persist; cross-origin; failed/stale saves; reload; mobile.');
 }finally{await browser?.close();await Promise.all([host,embed].map(s=>new Promise(r=>s.close(r))));}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
